# Generated by Django 2.2.5 on 2021-12-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20211225_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quests',
            new_name='guests',
        ),
    ]
